// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viscon_ProjectC_Groep4;

#nullable disable

namespace Viscon_ProjectC_Groep4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231019082252_MergeConflictsFix")]
    partial class MergeConflictsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Companies", b =>
                {
                    b.Property<int>("Com_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Com_Id"));

                    b.Property<string>("Com_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Com_Id");

                    b.ToTable("Companies", "public");
                });

            modelBuilder.Entity("Entities.Departments", b =>
                {
                    b.Property<int>("Dep_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Dep_Id"));

                    b.Property<string>("Dep_Speciality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Dep_Id");

                    b.ToTable("Departments", "public");
                });

            modelBuilder.Entity("Entities.Machines", b =>
                {
                    b.Property<int>("Mach_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Mach_Id"));

                    b.Property<string>("Mach_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mach_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Mach_Id");

                    b.ToTable("Machines", "public");
                });

            modelBuilder.Entity("Entities.Messages", b =>
                {
                    b.Property<int>("Msg_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Msg_Id"));

                    b.Property<int>("Message_Sender")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Msg_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Msg_Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Msg_TickId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsTick_Id")
                        .HasColumnType("integer");

                    b.HasKey("Msg_Id");

                    b.HasIndex("TicketsTick_Id");

                    b.ToTable("Messages", "public");
                });

            modelBuilder.Entity("Entities.Tickets", b =>
                {
                    b.Property<int>("Tick_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Tick_Id"));

                    b.Property<int>("Tick_Creator_UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tick_DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tick_DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Tick_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tick_ExpectedToBeDone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Tick_Helper_UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Tick_MachId")
                        .HasColumnType("integer");

                    b.Property<string>("Tick_MadeAnyChanges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tick_Media")
                        .HasColumnType("text");

                    b.Property<int>("Tick_Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("Tick_Resolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Tick_Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Tick_Id");

                    b.HasIndex("Tick_Creator_UserId");

                    b.HasIndex("Tick_DepartmentId");

                    b.HasIndex("Tick_Helper_UserId");

                    b.HasIndex("Tick_MachId");

                    b.ToTable("Tickets", "public");
                });

            modelBuilder.Entity("Entities.Users", b =>
                {
                    b.Property<int>("Usr_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usr_Id"));

                    b.Property<int>("Usr_CompId")
                        .HasColumnType("integer");

                    b.Property<int>("Usr_DepId")
                        .HasColumnType("integer");

                    b.Property<string>("Usr_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usr_FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usr_LanguagePreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usr_LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Usr_PasswSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Usr_Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Usr_PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Usr_Role")
                        .HasColumnType("integer");

                    b.HasKey("Usr_Id");

                    b.HasIndex("Usr_CompId");

                    b.HasIndex("Usr_DepId");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("Entities.Messages", b =>
                {
                    b.HasOne("Entities.Tickets", "Tickets")
                        .WithMany()
                        .HasForeignKey("TicketsTick_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Entities.Tickets", b =>
                {
                    b.HasOne("Entities.Users", "Creator")
                        .WithMany()
                        .HasForeignKey("Tick_Creator_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("Tick_DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Users", "Helper")
                        .WithMany()
                        .HasForeignKey("Tick_Helper_UserId");

                    b.HasOne("Entities.Machines", "Machines")
                        .WithMany()
                        .HasForeignKey("Tick_MachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Departments");

                    b.Navigation("Helper");

                    b.Navigation("Machines");
                });

            modelBuilder.Entity("Entities.Users", b =>
                {
                    b.HasOne("Entities.Companies", "Companies")
                        .WithMany()
                        .HasForeignKey("Usr_CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("Usr_DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
